name: Terraform AWS Deployment

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
    
      - name: Configure Terraform Credential
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials": {"app.terraform.io": {"token": "${{ secrets.TF_CLOUD_TOKEN}}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: AWS Credential Configures
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Terraform Init code
      #   run: |
      #     cd src/envs/dev
      #     pwd
      #     terraform init
        
    #   - name: Terraform Plans
    #     run: |
    #       cd src/envs/dev
    #       pwd
    #       terraform plan -out=tfplan
